openedx/features/wikimedia_features/messenger/settings/common.py, openedx/features/wikimedia_features/messenger/static/css/ReactToastify.css, openedx/features/wikimedia_features/messenger/static/messenger/js/Messenger.js, openedx/features/wikimedia_features/messenger/static/messenger/js/MessengerContent.js, openedx/features/wikimedia_features/messenger/static/messenger/js/components/Conversation/index.js, openedx/features/wikimedia_features/messenger/static/messenger/js/components/Inbox/index.js, openedx/features/wikimedia_features/messenger/static/messenger/js/components/newMessageModal.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useClient.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useCreateUpdateMessages.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useInboxList.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useScrollObserver.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useSelectedInbox.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useUserSearch.js, openedx/features/wikimedia_features/messenger/templates/messenger.html, package-lock.json, package.json
Replaced [react-toasts ](https://www.npmjs.com/package/react-toasts)library with [react-toastify](https://www.npmjs.com/package/react-toastify) as uglify-js was giving syntax error on `react-toasts`.
=> Replace react-toasts with react-toastify library

openedx/features/wikimedia_features/admin_dashboard/static/admin_dashboard/js/course_reports.js
minor bug fix for single course report generation feature
=> bug fix in course report generation for single course

common/djangoapps/third_party_auth/pipeline.py, lms/envs/production.py, openedx/features/wikimedia_features/auth_backend.py
Custom OAUth2.0 back-end for Wikimedia IDP.
=> Add Wikimedia IDP Backend

openedx/features/wikimedia_features/messenger/api/v0/serializers.py, openedx/features/wikimedia_features/messenger/api/v0/views.py, openedx/features/wikimedia_features/messenger/models.py, openedx/features/wikimedia_features/messenger/static/messenger/js/MessengerContent.js, openedx/features/wikimedia_features/messenger/static/messenger/js/assets/spinner.js, openedx/features/wikimedia_features/messenger/static/messenger/js/components/Conversation/index.js, openedx/features/wikimedia_features/messenger/static/messenger/js/components/Inbox/index.js, openedx/features/wikimedia_features/messenger/static/messenger/js/components/newMessageModal.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useCreateUpdateMessages.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useInboxList.js, openedx/features/wikimedia_features/messenger/templates/messenger.html
Messenger UI implementation and enhancement
**Before**
**After**
=> Messenger UI implementation and enhancement

lms/templates/header/navbar-authenticated.html
Add messenger and reports page in navigation bar.
=> Navigation bar fix

lms/envs/common.py, lms/envs/production.py, openedx/features/wikimedia_features/email/utils.py
Use edX logo setting (DEFAULT_EMAIL_LOGO_URL).
=> Use edX logo settings

openedx/features/wikimedia_features/admin_dashboard/admin_task/api.py, openedx/features/wikimedia_features/admin_dashboard/admin_task/api_helper.py, openedx/features/wikimedia_features/admin_dashboard/course_reports.py, openedx/features/wikimedia_features/admin_dashboard/grades.py, openedx/features/wikimedia_features/admin_dashboard/static/admin_dashboard/js/course_reports.js, openedx/features/wikimedia_features/admin_dashboard/tasks.py, openedx/features/wikimedia_features/admin_dashboard/templates/course_report/course-reports.html, openedx/features/wikimedia_features/admin_dashboard/urls.py
Generate progress report for enrolled student in a course.
=> generate progress report for enrolled student in a course

openedx/features/wikimedia_features/messenger/static/messenger/js/components/Inbox/index.js
Inbox design feedback implementation
=> Inbox design feedback implementation

openedx/features/wikimedia_features/admin_dashboard/admin_task/api_helper.py, openedx/features/wikimedia_features/admin_dashboard/grades.py, openedx/features/wikimedia_features/admin_dashboard/runner.py, openedx/features/wikimedia_features/admin_dashboard/static/admin_dashboard/js/course_reports.js, openedx/features/wikimedia_features/admin_dashboard/static/css/main.css, openedx/features/wikimedia_features/admin_dashboard/tasks.py, openedx/features/wikimedia_features/admin_dashboard/templates/course_report/course-reports.html, openedx/features/wikimedia_features/admin_dashboard/utils.py
Fix changes in generate completion report and generate report for multiple courses.
=> Fix report for admin_dashboard

openedx/features/wikimedia_features/messenger/static/messenger/js/components/Conversation/index.js, openedx/features/wikimedia_features/messenger/static/messenger/js/hooks/useInboxList.js
Unread msgs count wasn;t working properly due to multiple rendering issue.
=> Fix unread msgs issue on innitial load'

lms/djangoapps/instructor/enrollment.py
Add logo_url in context of membership emails.
=> Fix broken logo image for membership emails

lms/djangoapps/instructor/enrollment.py, openedx/features/wikimedia_features/wikimedia_general/apps.py, openedx/features/wikimedia_features/wikimedia_general/settings/common.py, openedx/features/wikimedia_features/wikimedia_general/signals.py, setup.py
Create configured default course mode at the time of new course creation
=> Stage Release 01-11-21

lms/djangoapps/certificates/views/webview.py, lms/static/certificates/sass/_overrides.scss, lms/templates/certificates/_accomplishment-rendering.html
Course image added to certificate
=> Course image added to certificate

lms/static/certificates/sass/_overrides.scss
Fix: Certificate layout fixes for short text.
=> Certificate Layout fixes

cms/static/js/views/course_rerun.js, cms/static/sass/elements/_forms.scss
Course re-run Translation restyles
=> Rerun form dynamic styles

cms/static/js/views/course_rerun.js
Update javascript so that it does not send language arguments in basic rerun
=> fix basic course language issue

cms/djangoapps/contentstore/views/course.py, cms/static/js/views/course_blocks_mapping.js, cms/static/js/views/pages/course_outline.js, cms/templates/course_outline.html, cms/templates/js/course-blocks-mapping.underscore, openedx/features/wikimedia_features/meta_translations/admin.py, openedx/features/wikimedia_features/meta_translations/apps.py, openedx/features/wikimedia_features/meta_translations/models.py, openedx/features/wikimedia_features/meta_translations/urls.py, openedx/features/wikimedia_features/meta_translations/utils.py, openedx/features/wikimedia_features/meta_translations/views.py
- On course-outline page of studio, add new button "Mapping"
- On mapping button click -> retrieve all data from course-outline and map it translation table.
=> Multilingual Feature -> map course blocks button

openedx/features/wikimedia_features/meta_translations/management/commands/sync_untranslated_strings_to_meta_from_edx.py
```  
$ ./manage.py cms sync_untranslated_strings_to_meta_from_edx
It will only show all updated blocks that are ready to send.
$ ./manage.py cms sync_untranslated_strings_to_meta_from_edx --commit
It will send API calls of Wiki Meta to update message groups.
```
- #65
=> Add --commit argument to send translation cron job

openedx/features/wikimedia_features/meta_translations/management/commands/sync_untranslated_strings_to_meta_from_edx.py, requirements/edx/base.txt, requirements/edx/development.txt
- Add "asyncio" and "aiohttp" in edx requirements file
- Update title format in send_translation command.
**Note: make_upgrade is not working, that's why adding requirements in base.in and development.in files directly.**
=> Update edx requirements to install aiohttp and asyncio

openedx/features/wikimedia_features/meta_translations/static/translations/js/TranslationContent.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/client/index.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Accordion.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Actions.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Sections.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Subsections.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Unit.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Units.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/hooks/useFetch.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/hooks/useUpdate.js, openedx/features/wikimedia_features/meta_translations/templates/translations.html
Include approve translation feature
**Go to**
`<your-studio-url>/meta_translations/`
select the rerun course from the dropdown after selecting the base course
expand section and subsection to review translations and click on the check icon to approve them.
=> Multilingual Feature -> Approve Translations

common/static/common/js/discussion/utils.js
=> A ping/mention function on discussion forum

cms/djangoapps/contentstore/views/course.py, cms/static/js/views/course_blocks_mapping.js, cms/templates/course_outline.html, cms/templates/js/course-blocks-mapping.underscore, openedx/features/wikimedia_features/meta_translations/meta_client.py, openedx/features/wikimedia_features/meta_translations/models.py, openedx/features/wikimedia_features/meta_translations/views.py
- Hide the mapping button for normal courses
- On mapping-button click of translated course. => Run mapping of base course before running mapping of the translated version,
=> Mapping button and function changes.

openedx/features/wikimedia_features/meta_translations/api/v0/utils.py, openedx/features/wikimedia_features/meta_translations/settings/common.py, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Unit.js, openedx/features/wikimedia_features/meta_translations/transformers/wiki_transformer.py, openedx/features/wikimedia_features/meta_translations/wiki_components.py
=> Multilingual Feature -> Add transformer for video component

cms/djangoapps/contentstore/views/course.py, cms/static/js/models/settings/course_details.js, cms/static/js/views/settings/main.js, cms/static/js/views/utils/wiki_utils.js, cms/templates/settings.html, openedx/features/wikimedia_features/meta_translations/models.py, openedx/features/wikimedia_features/meta_translations/utils.py
Add new course settings for destination course -> update course flag from Destination to Source.
Styling is pending to convert this checkbox in Switch.
=> Add new course settings to update course flag Destination -> Source

openedx/features/wikimedia_features/email/utils.py, openedx/features/wikimedia_features/wikimedia_general/templates/wikimedia_general/edx_ace/threadmentionnotification/email/subject.txt
Update Email subject for discussion forum mentioned users email.
Feedback got from client: Add wiki learn to subject.
=> Update Email subject for discussion forum mentioned users email

cms/djangoapps/contentstore/views/course.py, openedx/features/wikimedia_features/meta_translations/urls.py, openedx/features/wikimedia_features/meta_translations/utils.py, openedx/features/wikimedia_features/meta_translations/views.py
Apply mapping automatically at the time of translated re-run creation.
=> Run mapping on translated rerun at the time of creation

openedx/features/wikimedia_features/admin_dashboard/admin.py, openedx/features/wikimedia_features/admin_dashboard/admin_task/api.py, openedx/features/wikimedia_features/admin_dashboard/course_reports.py, openedx/features/wikimedia_features/admin_dashboard/course_versions/task_helper.py, openedx/features/wikimedia_features/admin_dashboard/course_versions/utils.py, openedx/features/wikimedia_features/admin_dashboard/static/admin_dashboard/js/course_reports.js, openedx/features/wikimedia_features/admin_dashboard/tasks.py, openedx/features/wikimedia_features/admin_dashboard/templates/course_report/course-reports.html, openedx/features/wikimedia_features/admin_dashboard/urls.py
[edX_base_en_base_versions_info_total_2022-06-16-1026.csv](https://github.com/wikimedia/edx-platform/files/8920032/edX_base_en_base_versions_info_total_2022-06-16-1026.csv)
[edX_base_en_base_versions_info_detailed_2022-06-16-1025.csv](https://github.com/wikimedia/edx-platform/files/8920033/edX_base_en_base_versions_info_detailed_2022-06-16-1025.csv)
[ERRORS_edX_base_en_base_versions_info_2022-06-16-0804.csv](https://github.com/wikimedia/edx-platform/files/8920034/ERRORS_edX_base_en_base_versions_info_2022-06-16-0804.csv)
=> Course versions Reports

openedx/features/wikimedia_features/meta_translations/management/commands/sync_untranslated_strings_to_meta_from_edx.py
Ticket link: https://edlyio.atlassian.net/browse/WM-130
=> Update send tranlsations command - uncomment metadata key

openedx/features/wikimedia_features/meta_translations/api/v0/serializers.py, openedx/features/wikimedia_features/meta_translations/api/v0/urls.py, openedx/features/wikimedia_features/meta_translations/api/v0/utils.py, openedx/features/wikimedia_features/meta_translations/api/v0/views.py, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Accordion.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Actions.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Sections.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Subsections.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Unit.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/hooks/useFetch.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/hooks/useUpdate.js, openedx/features/wikimedia_features/meta_translations/templates/translations.html, openedx/features/wikimedia_features/meta_translations/utils.py
=> Multilingual Feature => add approve all in meta-translation page

cms/templates/js/course-blocks-mapping.underscore, cms/templates/settings.html, openedx/features/wikimedia_features/meta_translations/static/translations/js/TranslationContent.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Actions.js
[WM-144](https://edlyio.atlassian.net/browse/WM-144)
- Fix UI issues.
Related theme PR https://github.com/wikimedia/wikilearn-edx-theme/pull/36
=> Fix UI issues

cms/static/js/views/course_blocks_mapping.js, cms/static/js/views/pages/container.js, cms/static/js/views/utils/xblock_utils.js, cms/static/js/views/xblock_string_field_editor.js
=> Show warning msg  of mapping lost. on base course block deletion

cms/djangoapps/contentstore/views/course.py
Bug:
- Error on rerun creation
=> Fix rerun bug

cms/static/js/views/utils/wiki_utils.js, cms/static/js/views/xblock_string_field_editor.js
Bug:
- Edit warning was also being shown on new block creation along with block edit.
=> Fix warning bug

openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Accordion.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Actions.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Unit.js
=> Multilingual Feature -> UI fixes

openedx/features/wikimedia_features/meta_translations/api/v0/utils.py, openedx/features/wikimedia_features/meta_translations/meta_client.py, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Accordion.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Actions.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Sections.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Subsections.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Unit.js, openedx/features/wikimedia_features/meta_translations/static/translations/js/components/Units.js
- #137
- #138
- https://github.com/wikimedia/wikilearn-edx-theme/pull/45
=> Stage Release 28-06-2021 (Wikimedia - Phase 2 - Add Redirect Meta Server URLS + Bug Fixes)

openedx/features/wikimedia_features/admin_dashboard/course_versions/utils.py
To extract language 
On Local machine (LMS side):
- Course from modulestore i.e get_course_by_id is working fine.
- CourseOverview returns language None
On servers (LMS side):
- Course from modulestore i.e get_course_by_id is not working fine and always returns base course language instead of rerun language.
- CourseOverview is wokring fine.
Have to add both checks, to run code smoothly both on local and server's enviroments.
=> Fix version reports bug - course language

cms/static/js/features_jsx/studio/CourseOrLibraryListing.jsx
=> Multilingual Feature -> Change position of badge

requirements/edx/base.txt, requirements/edx/development.txt
Ticket: https://edlyio.atlassian.net/browse/WM-154
=> Update requirements file to install sysadmin plugin

openedx/features/wikimedia_features/wikimedia_general/tab.py, openedx/features/wikimedia_features/wikimedia_general/templates/wikimedia_general/wikimedia_progress_fragment.html, openedx/features/wikimedia_features/wikimedia_general/urls.py, openedx/features/wikimedia_features/wikimedia_general/views.py, setup.py
https://github.com/wikimedia/wikilearn-edx-theme/pull/55
=> Add custom progress tab

lms/templates/navigation/bootstrap/navbar-authenticated.html, lms/templates/navigation/navbar-logo-header.html
=> Show title on hover the truncated text

common/lib/xmodule/xmodule/course_module.py, openedx/features/wikimedia_features/wikimedia_general/templates/wikimedia_general/wikimedia_progress_fragment.html, openedx/features/wikimedia_features/wikimedia_general/views.py
=> Customize visibility of the score tab

lms/templates/courses_list.html, lms/templates/main_django.html, lms/templates/wiki/base.html
=> Make lms & studio responsive for right-to-left languages

conf/locale/ar/LC_MESSAGES/django.po, conf/locale/ar/LC_MESSAGES/djangojs.po
Reverts wikimedia/edx-platform#268
=> Revert "Add changed translation files"

.github/workflows/generate-translations.yml, .gitignore, .tx/config-lilac, conf/locale/config.yaml, openedx/features/wikimedia_features/wikimedia_general/management/commands/translatewiki.py
=> Stage Release 27-12-23 (Localization updates)

openedx/features/wikimedia_features/wikimedia_general/api/v0/urls.py, openedx/features/wikimedia_features/wikimedia_general/api/v0/views.py, openedx/features/wikimedia_features/wikimedia_general/apps.py, openedx/features/wikimedia_features/wikimedia_general/urls.py
This PR adds a url to fetch course font. Endpoint is available at:
{{EDX_HOST}}/wikimedia_general/api/v0/wiki_metadata/{{COURSE_KEY}}
=> Add course font API
